### ISSUE TITLE
Can you help us to fight MEV bots ?

### ISSUE THREAD

**Issue by tsarbuig** [valamidev/web3-defi-honeypot-and-slippage-checker#13]
Hey bro, we've been struggling with MEV bots now on token launches on ETH...

I know this is off-topic here but it's the only way I found to reach you :)

Some sniping bots are developing Smart contract to fight them, any idea on how to do the same ? 
![image](https://user-images.githubusercontent.com/70858574/219904490-3576e76f-f8e0-42b1-b71b-23bb47adf060.png)

Thanks bro :)

**Comment by valamidev** [comment]
I would say, since most MEV bots are only reading the mempool for specified transactions, with having a "middle" contract with obfuscate interface is a possible way to avoid them. 

But, still at a snipping is really hard to choose between an acceptable prices vs. possible failed transaction and loss of txCost. 
MEV will always have advantage, because they know what is your limit and they only need to calculate can they upfront it or not.
